### ISSUE TITLE
How to get the results of MonoCon?

### ISSUE THREAD

**Issue by moyanouo** [mingyuShin/Depth-metric-learning-3d-object-detection#2]
Hello, this is great work. The results I reproduced are similar to the monodle you mentioned. In your paper, you mentioned "MonoCon+Ours" many times. Could you please show this version and the corresponding Weight file? Thank you, looking forward to reply

**Comment by mingyuShin** [comment]
Thank you for your interest. We have released the monodle code, which is the easiest for code cleaning. If you want to obtain our results from MonoCon, you can use the MonoCon github code, apply _update_K_return_loss to the feature before entering MonoCon's head, and add the object-wise depth map loss as an auxiliary head. Thank you.

**Comment by moyanouo** [comment]
您好，我是范智玮。感谢您的来信，我将尽快查看并回复。祝您身体健康，万事如意。

**Comment by moyanouo** [comment]
您好，我是范智玮。感谢您的来信，我将尽快查看并回复。祝您身体健康，万事如意。
